apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grocery-automation-backend
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # Maximum number of instances
        autoscaling.knative.dev/maxScale: '10'
        # Minimum number of instances
        autoscaling.knative.dev/minScale: '1'
        # CPU allocation
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containers:
      - image: us-west2-docker.pkg.dev/grocery-automation-467922/grocery-automation-backend/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
        - name: PORT
          value: '8080'
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
      serviceAccountName: grocery-app-deployer@grocery-automation-467922.iam.gserviceaccount.com